name: Weekly Insta Post

on:
  schedule:
    - cron: '0 10 * * 1'  # Montags 12:00 Uhr (DE)
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt

      - name: Inhalt generieren (Zitat + Bild mit Text)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_content.py

      - name: Bild posten
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        run: |
          python auto_post.py
