name: Weekly Insta Post

on:
  schedule:
    - cron: '0 10 * * 1'  # Jeden Montag um 10:00 UTC = 12:00 Uhr Deutschlandzeit
  workflow_dispatch:      # Manuell auslösbar

jobs:
  insta-post:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt

      - name: Post auf Instagram machen
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        run: |
          python auto_post.py
