name: Daily Run

on:
  schedule:
    - cron: '0 13 * * *'  # Every day at 13:00 UTC
  workflow_dispatch:  # Optional: manual trigger

permissions:
  contents: write


jobs:
  daily-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install instagrapi pillow requests
          
      - name: Decode session.json from Secret
        run: |
          echo "${{ secrets.IG_SESSION }}" | base64 -d > session.json
          
      - name: Run daily_run.py
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          IG_USERNAME_MAYA: ${{ secrets.IG_USERNAME_MAYA }}
          IG_PASSWORD_MAYA: ${{ secrets.IG_PASSWORD_MAYA }}
          IG_SESSION: ${{ secrets.IG_SESSION }}
          IG_TOKEN_ELIAS: ${{ secrets.IG_TOKEN_ELIAS }}
          IG_USERID_ELIAS: ${{ secrets.IG_USERID_ELIAS }}
          IG_TOKEN_MAYA: ${{ secrets.IG_TOKEN_MAYA }}
          IG_USERID_MAYA: ${{ secrets.IG_USERID_MAYA }}


        run: python daily_run.py
      
      - name: Set git user
        run: |
          git config user.email "kernline.mk@gmail.com"
          git config user.name "Kernle0110"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto-post: Moved posted image to archive [skip ci]" || echo "Nothing to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
